#!/bin/bash
git add -A
git add .
git add --all
git add -u .
git commit -m "$1"
#git pull u116 master
#git push u116 master
git pull sloninfobox master
git push sloninfobox master

echo -e "\e[0;33m==============================================================================================\e[0m"
echo -e "\e[0;32m start deploy to tests\e[0m"
echo -e "\e[0;33m==============================================================================================\e[0m"
RAILS_ENV=tests cap tests deploy --trace

echo -e "\e[0;33m==============================================================================================\e[0m"
echo -e "\e[0;32m restart tests puma server\e[0m"
echo -e "\e[0;33m==============================================================================================\e[0m"
RAILS_ENV=tests cap tests puma:restart || RAILS_ENV=tests cap tests puma:start

