#!/bin/bash
#deploy to production server script
./sync_repo "$1"
echo -e "\e[0;33m==============================================================================================\e[0m"
echo -e "\e[0;32m start deploy to tests\e[0m"
echo -e "\e[0;33m==============================================================================================\e[0m"
RAILS_ENV=tests cap tests deploy --trace

echo -e "\e[0;33m==============================================================================================\e[0m"
echo -e "\e[0;32m restart tests puma server\e[0m"
echo -e "\e[0;33m==============================================================================================\e[0m"
RAILS_ENV=tests cap tests puma:restart || RAILS_ENV=tests cap tests puma:start

